os:
  - linux
services:
  - docker
language: java
cache:
  directories:
    - $HOME/.m2
jdk:
  - adopt@1.12
env:
  global:
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - JHI_DISABLE_WEBPACK_LOGS=true
    - NG_CLI_ANALYTICS="false"
    - MAVEN_USER_HOME=$HOME/.m2/repository/
    - TRAVIS_JDK=adopt@1.12
install:
  - unset _JAVA_OPTIONS
  - echo $TRAVIS_JDK
  - ls /home/travis/bin
  - export JAVA_HOME="$TRAVIS_JDK"
  - java -version
script:
  - chmod +x mvnw
  - java -version
  - ./mvnw -ntp checkstyle:check
  - ./mvnw -ntp clean verify
  - ./mvnw -ntp verify -Pprod -DskipTests
  - ./mvnw -ntp com.heroku.sdk:heroku-maven-plugin:2.0.5:deploy -DskipTests -Pprod -Dheroku.buildpacks=heroku/jvm -Dheroku.appName=kacetal-library-stock
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
